### ISSUE TITLE
Hook issues using @prefresh/nollup

### ISSUE THREAD

**Issue by hanswilw** [JoviDeCroock/prefresh#127] opened 2020-08-03 13:05 UTC
I came across an issue where the state is not being persisted when using components defined in the same file. It compiles and runs, but once prefresh and nollup injects new code for it, the hook state is reset to 0. Preact example provided [here](https://github.com/hanswilw/nollup/commit/85a7d9e8818b7f2ee9425bb72180b144e5d0de7a)

Another related issue is when using hooks like `useMemo` inside components like [here](https://github.com/hanswilw/nollup/commit/c66c0f8c8215000c89a573ceb4c9ac7aba72d55d).
It exhibits `Uncaught TypeError: undefined is not a function` or `Uncaught (in promise) TypeError: $RefreshSig$ is not a function` when HMR injects this code.

I did verify that this works properly with the react-refresh example, so I guess these are related to the @prefresh/nollup plugin. Maybe this is @PepsRyuu's domain? :)

**Comment by JoviDeCroock** [comment] 2020-08-03 13:59
Hey @hanswilw 

Thanks for the well-illustrated bugs, helps a lot in me debugging this stuff.

About issue 1, the state will reset when you change the contents of a components hook body. Tried this in my own test https://github.com/JoviDeCroock/prefresh/tree/main/packages/nollup/example
This means that when I change the text of the buttons the hook state is kept, when I change the initial value of the `useCounter` hook it isn't kept.

Issue 2 seems to stem from this part https://github.com/JoviDeCroock/prefresh/blob/main/packages/nollup/src/index.js#L5 not being executed on that module. I don't think this is a prefresh issue. In general I don't think it's a good practice to use hooks inside of a loop. This is undeterministic and won't allow Preact to correctly relate hookStates together, generally this is better abstracted to a component which would deterministicaly handle that `useMemo` as its own rather than as a child.

**Comment by hanswilw** [comment] 2020-08-03 14:17
The first issue is when changing things outside of the hook, like the text as you mention. In the provided example if you change the text `Bugged counter:`, it still resets the hook to 0. If you do the same thing to the `Working counter` it does not reset. The only difference between them is that the bugged counter component is defined in the same file as it is used, while the working one is imported.

2: Right, makes sense – however it was cumbersome to figure out the cause of the error, and other people might stumble upon this as well. Atleast it is mentioned here now :)

**Comment by hanswilw** [comment] 2020-08-03 14:45
Hmm, is it? From what I read that is naming and export advices, not defining local components that uses hooks? I'd bet it is pretty common to create smaller helper components with hooks like I am trying to illustrate. Otherwise one can only have state persisting hooks in the exported component? Please enlighten me if I am missing something here 😅

Like here, changing `Counter:` text resets the useState to 0. Moving the hook to Component1, or splitting it out to its own file then it does not reset to 0.

```
const Component1 = () => {
  return (<div><h1>Title</h1><Component2 /></div>);
}

const Component2 = () => {
  const [count, setCount] = useState(0);
  return (<div>Counter: {count}</div>);
}

export default Component1;
```

**Comment by JoviDeCroock** [comment] 2020-08-03 14:48
That should not change the signature so there could be a bug there, I'll check it out later

**Comment by JoviDeCroock** [comment] 2020-08-03 16:53
@hanswilw for some reason in nollup this piece of code https://github.com/JoviDeCroock/prefresh/blob/main/packages/core/src/index.js#L30 is never reached which means that it bounces into an error here https://github.com/JoviDeCroock/prefresh/blob/main/packages/core/src/computeKey.js#L15 making it force reset.

**Comment by PepsRyuu** [comment] 2020-08-03 17:32
FYI, I am reading, but won't be able to test or investigate anything from a Nollup perspective until probably next week. (Enjoying some time off 🙂)

**Comment by hanswilw** [comment] 2020-08-03 17:40
Great, thanks for investigating so promptly! 🙌🏻

**Comment by JoviDeCroock** [comment] 2020-08-03 18:02
@hanswilw this seems to be intended behavior when a component is exported we can't link it to the changed file so if `Component2` isn't exported the safest assumption would be to reset hooks.

**Comment by JoviDeCroock** [comment] 2020-08-04 17:56
@hanswilw Fixed in https://github.com/JoviDeCroock/prefresh/pull/131/files

**Comment by JoviDeCroock** [comment] 2020-08-04 21:01
@hanswilw would you mind testing `@prefresh/nollup@0.7.0-alpha.0` this goes accompanied with `@prefresh/utils@0.3.0-alpha.0` and `@prefresh/core@0.8.0-alpha.0`

**Closed** 2020-08-06 08:11 UTC

**Comment by hanswilw** [comment] 2020-08-06 18:36
@JoviDeCroock looks like it is working well here! 👍
